# Generated by Django 4.2.9 on 2025-12-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_date_joined_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("kitchen", "Kitchen Staff"),
                ],
                default="cashier",
                max_length=20,
            ),
        ),
    ]
