# Generated by Django 4.2.9 on 2026-01-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_alter_outlet_options_and_more"),
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accessible_outlets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Outlets this user can access (for managers)",
                related_name="accessible_users",
                to="tenants.outlet",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary/default outlet for this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.outlet",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("tenant_owner", "Tenant Owner"),
                    ("manager", "Manager"),
                    ("cashier", "Cashier"),
                    ("kitchen", "Kitchen Staff"),
                ],
                default="cashier",
                max_length=20,
            ),
        ),
    ]
