# Generated by Django 4.2.9 on 2026-01-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="Device identifier (e.g., kiosk-001)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="source",
            field=models.CharField(
                choices=[
                    ("kiosk", "Kiosk"),
                    ("web", "Web/Mobile"),
                    ("cashier", "Cashier POS"),
                ],
                db_index=True,
                default="web",
                max_length=20,
            ),
        ),
    ]
