# Generated by Django 4.2.9 on 2026-01-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_device_id_order_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="kitchen_station_code",
            field=models.CharField(
                db_index=True,
                default="MAIN",
                help_text="Kitchen station code for routing (snapshot from product)",
                max_length=20,
            ),
        ),
    ]
