# Generated by Django 4.2.9 on 2026-01-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_add_location_model"),
        ("orders", "0003_add_kitchen_station_code_to_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this order group (e.g., GRP-20260106-ABCD)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("qris", "QRIS"),
                            ("ewallet", "E-Wallet"),
                            ("split", "Split Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("kiosk", "Kiosk"), ("web", "Web/Mobile")],
                        default="kiosk",
                        max_length=20,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, help_text="Kiosk device identifier", max_length=50
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Frontend session ID for tracking",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Physical location where orders were placed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_groups",
                        to="tenants.location",
                    ),
                ),
            ],
            options={
                "db_table": "order_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group this order belongs to (for multi-outlet payments)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="orders.ordergroup",
            ),
        ),
        migrations.AddIndex(
            model_name="ordergroup",
            index=models.Index(
                fields=["-created_at", "payment_status"],
                name="order_group_created_eb0bb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordergroup",
            index=models.Index(
                fields=["location", "-created_at"],
                name="order_group_locatio_af419c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordergroup",
            index=models.Index(
                fields=["session_id"], name="order_group_session_9f0b4d_idx"
            ),
        ),
    ]
