# Generated by Django 4.2.9 on 2026-01-07 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_add_order_group_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ordergroup",
            name="order_group_locatio_af419c_idx",
        ),
        migrations.RemoveField(
            model_name="ordergroup",
            name="location",
        ),
    ]
