# Generated by Django 4.2.9 on 2026-01-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0013_opsi2_rename_location_to_store"),
        ("orders", "0005_opsi2_rename_location_to_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergroup",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical store where orders were placed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_groups",
                to="tenants.store",
            ),
        ),
        migrations.AddIndex(
            model_name="ordergroup",
            index=models.Index(
                fields=["store", "-created_at"], name="order_group_store_i_1ccb2b_idx"
            ),
        ),
    ]
