# Generated by Django 4.2.9 on 2026-01-08 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0014_storeoutlet_alter_outlet_options_and_more"),
        ("orders", "0006_opsi2_rename_location_to_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical store where this order was placed (for kitchen display routing)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="tenants.store",
            ),
        ),
    ]
