# Generated by Django 4.2.9 on 2025-12-28 00:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("tenants", "0002_alter_outlet_options_and_more"),
        ("products", "0002_outletproduct_remove_category_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Promotion name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional promo code for customers to enter",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "promo_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Discount"),
                            ("fixed", "Fixed Amount Discount"),
                            ("buy_x_get_y", "Buy X Get Y"),
                            ("bundle", "Bundle Deal"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount amount (percentage or fixed)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount for percentage-based promos",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum purchase amount to qualify",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "buy_quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="Buy X quantity (for Buy X Get Y promos)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "get_quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="Get Y quantity (for Buy X Get Y promos)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Promotion start date and time"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Promotion end date and time"),
                ),
                ("monday", models.BooleanField(default=True)),
                ("tuesday", models.BooleanField(default=True)),
                ("wednesday", models.BooleanField(default=True)),
                ("thursday", models.BooleanField(default=True)),
                ("friday", models.BooleanField(default=True)),
                ("saturday", models.BooleanField(default=True)),
                ("sunday", models.BooleanField(default=True)),
                (
                    "time_start",
                    models.TimeField(
                        blank=True, help_text="Daily start time (optional)", null=True
                    ),
                ),
                (
                    "time_end",
                    models.TimeField(
                        blank=True, help_text="Daily end time (optional)", null=True
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times this promo can be used (total)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "usage_limit_per_customer",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum uses per customer",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Current usage count",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("paused", "Paused"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured promotions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant who owns this promotion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Customer ID, phone, or session identifier",
                        max_length=255,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual discount amount applied",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_usages",
                        to="orders.order",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["promotion", "customer_identifier"],
                        name="promotions__promoti_a011b1_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="promotions__created_8f3bf6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override discount for this specific product",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority promos are applied first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_promotions",
                        to="products.product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_products",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
                "unique_together": {("promotion", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["tenant", "status"], name="promotions__tenant__424da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["start_date", "end_date"], name="promotions__start_d_283aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["is_active", "status"], name="promotions__is_acti_eadd5e_idx"
            ),
        ),
    ]
