# Generated by Django 4.2.9 on 2026-01-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionproduct",
            name="product_role",
            field=models.CharField(
                choices=[
                    ("buy", "Buy Product (X)"),
                    ("get", "Get Product (Y)"),
                    ("both", "Both Buy and Get"),
                ],
                default="both",
                help_text="Role of this product in Buy X Get Y promotions",
                max_length=10,
            ),
        ),
    ]
