# Generated by Django 4.2.9 on 2025-12-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0002_alter_outlet_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "membership_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("membership_tier", models.CharField(default="regular", max_length=50)),
                ("points", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_subscribed", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_order_at", models.DateTimeField(blank=True, null=True)),
                (
                    "preferred_outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_customers",
                        to="tenants.outlet",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="customers_tenant__3bec53_idx",
                    ),
                    models.Index(
                        fields=["tenant", "phone"], name="customers_tenant__a2831a_idx"
                    ),
                    models.Index(
                        fields=["tenant", "membership_tier"],
                        name="customers_tenant__947f37_idx",
                    ),
                ],
                "unique_together": {("tenant", "phone")},
            },
        ),
    ]
