# Generated by Django 4.2.9 on 2025-12-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outlet",
            options={"ordering": ["tenant", "name"]},
        ),
        migrations.RemoveConstraint(
            model_name="outlet",
            name="unique_tenant_outlet_slug",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="address",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="contact_phone",
        ),
        migrations.AddField(
            model_name="outlet",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outlet",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="tenant",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="postal_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(default="#FF6B35", max_length=7),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(default="#F7931E", max_length=7),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="service_charge_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name="outlet",
            unique_together={("tenant", "slug")},
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="operating_hours",
        ),
    ]
