# Generated by Django 4.2.9 on 2026-01-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_alter_outlet_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlet",
            name="websocket_url",
            field=models.CharField(
                blank=True,
                default="ws://localhost:3001",
                help_text="WebSocket URL for Kitchen Sync Server (e.g., ws://192.168.1.10:3001)",
                max_length=255,
            ),
        ),
    ]
