# Generated by Django 4.2.9 on 2026-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_outlet_websocket_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlet",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
