# Generated by Django 4.2.9 on 2026-01-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_alter_outlet_postal_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name (e.g., "Food Kitchen", "Drink Bar")',
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Short code (e.g., "FOOD", "DRINK", "GRILL")',
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower number = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_stations",
                        to="tenants.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "kitchen_stations",
                "ordering": ["outlet", "sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["outlet", "is_active"],
                        name="kitchen_sta_outlet__1db8cb_idx",
                    )
                ],
                "unique_together": {("outlet", "code")},
            },
        ),
    ]
