# Generated by Django 4.2.9 on 2026-01-05 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_kitchenstationtype"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="kitchenstationtype",
            new_name="kitchen_sta_code_3377ca_idx",
            old_name="kitchen_sta_code_idx",
        ),
        migrations.RenameIndex(
            model_name="kitchenstationtype",
            new_name="kitchen_sta_tenant__70b6c0_idx",
            old_name="kitchen_sta_tenant_idx",
        ),
    ]
