# Generated by Django 4.2.9 on 2026-01-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenants",
            "0007_rename_kitchen_sta_code_idx_kitchen_sta_code_3377ca_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Location identifier code (e.g., YOGYA-FC-01, MALL-GF-NORTH)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Location display name (e.g., "Yogya Food Court - Level 3")',
                        max_length=200,
                    ),
                ),
                ("address", models.TextField(help_text="Full address of the location")),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "kiosk_qr_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique QR code identifier for kiosk setup",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "enable_multi_outlet_payment",
                    models.BooleanField(
                        default=True,
                        help_text="Allow customers to order from multiple outlets in one transaction",
                    ),
                ),
                (
                    "payment_split_method",
                    models.CharField(
                        choices=[
                            ("proportional", "Proportional to Order Total"),
                            ("even", "Split Evenly"),
                            ("manual", "Manual Split"),
                        ],
                        default="proportional",
                        help_text="How to split payment across multiple outlets",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="locations_code_a9dafe_idx"
                    ),
                    models.Index(
                        fields=["kiosk_qr_code"], name="locations_kiosk_q_710aae_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="outlet",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical location where this outlet is located (food court, mall, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outlets",
                to="tenants.location",
            ),
        ),
    ]
