# Generated by Django 4.2.9 on 2026-01-07 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_add_location_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["tenant", "is_active"], name="locations_tenant__58f9fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_location_code_per_tenant"
            ),
        ),
    ]
