# Generated by Django 4.2.9 on 2026-01-07 01:12

from django.db import migrations


def assign_locations_to_tenants(apps, schema_editor):
    """
    Assign existing locations to their tenants based on outlets
    If location has outlets, use the tenant from those outlets
    Otherwise, assign to first available tenant
    """
    Location = apps.get_model('tenants', 'Location')
    Tenant = apps.get_model('tenants', 'Tenant')
    Outlet = apps.get_model('tenants', 'Outlet')
    
    # Get first tenant as default
    default_tenant = Tenant.objects.first()
    
    if not default_tenant:
        # No tenants exist, skip
        return
    
    for location in Location.objects.filter(tenant__isnull=True):
        # Try to find tenant from outlets at this location
        outlet = Outlet.objects.filter(location=location).first()
        
        if outlet and outlet.tenant:
            location.tenant = outlet.tenant
        else:
            location.tenant = default_tenant
        
        location.save()


def reverse_assign(apps, schema_editor):
    """Reverse: set all tenant FKs to null"""
    Location = apps.get_model('tenants', 'Location')
    Location.objects.all().update(tenant=None)


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0009_add_tenant_to_location"),
    ]

    operations = [
        migrations.RunPython(assign_locations_to_tenants, reverse_assign),
    ]
