# Generated by Django 4.2.9 on 2026-01-07 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_assign_locations_to_default_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this location",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="tenants.tenant",
            ),
        ),
    ]
