# Generated by Django 4.2.9 on 2026-01-07 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0011_make_location_tenant_required"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_location_code_per_tenant",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="locations_tenant__58f9fb_idx",
        ),
        migrations.RemoveField(
            model_name="location",
            name="tenant",
        ),
    ]
