# Generated by Django 4.2.9 on 2026-01-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_opsi2_rename_location_to_store"),
        ("tenants", "0012_remove_location_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Store identifier code (e.g., YOGYA-KAPATIHAN, BORMA-DAGO)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Store display name (e.g., "Yogya Kapatihan", "Borma Dago")',
                        max_length=200,
                    ),
                ),
                ("address", models.TextField(help_text="Full address of the location")),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "kiosk_qr_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique QR code identifier for kiosk setup",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "enable_multi_outlet_payment",
                    models.BooleanField(
                        default=True,
                        help_text="Allow customers to order from multiple outlets in one transaction",
                    ),
                ),
                (
                    "payment_split_method",
                    models.CharField(
                        choices=[
                            ("proportional", "Proportional to Order Total"),
                            ("even", "Split Evenly"),
                            ("manual", "Manual Split"),
                        ],
                        default="proportional",
                        help_text="How to split payment across multiple outlets",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Retail company that owns this store (e.g., YOGYA, BORMA)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "stores",
                "ordering": ["tenant", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="location",
        ),
        migrations.AddField(
            model_name="outlet",
            name="brand_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Brand name (e.g., Chicken Sumo, Magic Oven, Magic Pizza)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="name",
            field=models.CharField(
                help_text="Full outlet name (auto-generated: brand_name - store_name)",
                max_length=200,
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AddField(
            model_name="outlet",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical store where this outlet/brand is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outlets",
                to="tenants.store",
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["tenant", "is_active"], name="stores_tenant__8f6057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["code", "is_active"], name="stores_code_9d9c64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["kiosk_qr_code"], name="stores_kiosk_q_2c50f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("tenant", "code")},
        ),
    ]
