# Generated by Django 4.2.9 on 2026-01-08 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0013_opsi2_rename_location_to_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreOutlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this brand is currently active at this store",
                    ),
                ),
                (
                    "custom_opening_time",
                    models.TimeField(
                        blank=True,
                        help_text="Override store opening time for this brand",
                        null=True,
                    ),
                ),
                (
                    "custom_closing_time",
                    models.TimeField(
                        blank=True,
                        help_text="Override store closing time for this brand",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order in kiosk UI (lower number = first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "store_outlets",
                "ordering": ["store", "display_order", "outlet__brand_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="outlet",
            options={"ordering": ["tenant", "brand_name"]},
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="address",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="city",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="opening_time",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="province",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="store",
        ),
        migrations.AddField(
            model_name="store",
            name="closing_time",
            field=models.TimeField(
                blank=True, help_text="Store closing time (e.g., 21:00:00)", null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="opening_time",
            field=models.TimeField(
                blank=True, help_text="Store opening time (e.g., 08:00:00)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="brand_name",
            field=models.CharField(
                help_text="Brand name (e.g., Chicken Sumo, Magic Oven, Magic Pizza)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="name",
            field=models.CharField(
                help_text="Display name (usually same as brand_name)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="tenant",
            field=models.ForeignKey(
                help_text="Retail company that owns this brand",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outlets",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="outlet",
            index=models.Index(
                fields=["tenant", "is_active"], name="outlets_tenant__147abe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outlet",
            index=models.Index(
                fields=["brand_name"], name="outlets_brand_n_5d5b19_idx"
            ),
        ),
        migrations.AddField(
            model_name="storeoutlet",
            name="outlet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_outlets",
                to="tenants.outlet",
            ),
        ),
        migrations.AddField(
            model_name="storeoutlet",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_outlets",
                to="tenants.store",
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="stores",
            field=models.ManyToManyField(
                help_text="Stores where this brand is available",
                related_name="outlets",
                through="tenants.StoreOutlet",
                to="tenants.store",
            ),
        ),
        migrations.AddIndex(
            model_name="storeoutlet",
            index=models.Index(
                fields=["store", "is_active"], name="store_outle_store_i_a3a471_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeoutlet",
            index=models.Index(
                fields=["outlet", "is_active"], name="store_outle_outlet__34708e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storeoutlet",
            unique_together={("store", "outlet")},
        ),
    ]
