# Generated by Django 4.2.9 on 2025-12-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_alter_outlet_options_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlet_products",
                        to="tenants.outlet",
                    ),
                ),
            ],
            options={
                "db_table": "outlet_products",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="productmodifier",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productmodifier",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="ProductOutletAvailability",
        ),
        migrations.AddField(
            model_name="outletproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outlet_products",
                to="products.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="outletproduct",
            unique_together={("outlet", "product")},
        ),
    ]
