# Generated by Django 4.2.9 on 2025-12-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_outletproduct_remove_category_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodifier",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifiers",
                to="products.product",
            ),
        ),
    ]
