# Generated by Django 4.2.9 on 2026-01-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_alter_outlet_options_and_more"),
        ("products", "0003_alter_productmodifier_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, product is only available at this outlet. Leave blank for all outlets.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.outlet",
            ),
        ),
    ]
