# Generated by Django 4.2.9 on 2026-01-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_kitchenstation"),
        ("products", "0004_product_outlet"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kitchen_station",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign product to specific kitchen station. Leave blank to show in all kitchens.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="tenants.kitchenstation",
            ),
        ),
    ]
