# Generated by Django 4.2.9 on 2026-01-08 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0014_storeoutlet_alter_outlet_options_and_more"),
        ("products", "0006_category_based_routing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["outlet", "sort_order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["outlet", "category", "name"]},
        ),
        migrations.AddField(
            model_name="category",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Brand that owns this category (e.g., Chicken Sumo, Magic Oven)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenants.outlet",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Brand that owns this product (e.g., Chicken Sumo, Magic Oven)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.outlet",
            ),
        ),
        migrations.AddField(
            model_name="productmodifier",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text='Outlet/Brand for global modifiers (e.g., all Chicken Sumo products can have "Extra Spicy")',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifiers",
                to="tenants.outlet",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="tenant",
            field=models.ForeignKey(
                help_text="Automatically set from outlet.tenant",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                help_text="Automatically set from outlet.tenant",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="productmodifier",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific product (leave empty for global outlet modifiers)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifiers",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["outlet", "is_active"], name="categories_outlet__844c5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tenant", "is_active"], name="categories_tenant__bf6fd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["outlet", "is_active"], name="products_outlet__bf5122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "is_active"], name="products_tenant__76cb13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_categor_9e60b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmodifier",
            index=models.Index(
                fields=["product", "is_active"], name="product_mod_product_2caadd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmodifier",
            index=models.Index(
                fields=["outlet", "is_active"], name="product_mod_outlet__374b95_idx"
            ),
        ),
    ]
